version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:21.7.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build

  test:
    docker:
      - image: cimg/node:21.7.1
    steps:
      - checkout
      - run:
          name: Insall dependencies
          command: npm install
      - run:
          name: Test API
          command: npm run test

  deploy:
    docker:
      - image: cimg/node:21.7.1
    steps:
      - checkout
      - run:
          name: Deploy to Render
          command: |
            curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_KFL0gfdDuz19qLTXANmEh6sz2a8n/5lbUS26NeZ
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
